server.port=${PORT:3004}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/spaceship}
spring.datasource.username=${POSTGRES_USER:spaceship}
spring.datasource.password=${POSTGRES_PASSWORD:spaceship}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.serialization.write-dates-as-timestamps=false
