source "https://rubygems.org"

ruby "~> 3.3.0"

gem "rails", "~> 7.2.2"
gem "pg", "~> 1.5"
gem "puma", "~> 6.6"
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
end
